### ISSUE TITLE
Does not connect behind a proxy

### ISSUE THREAD

**Issue by parmentf** [joelnet/the-terminal-cli#1]
Strange behaviour, even if you try to connect to 127.0.0.1, when your `http_proxy` environment variables are set:

```bash
$ ./src/bin.js http://127.0.0.1:18000
Fatal Error: Error: Request failed with status code 503
    at createError (/home/parmentf/prog/experiments/the-terminal-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/parmentf/prog/experiments/the-terminal-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/parmentf/prog/experiments/the-terminal-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

even though `no_proxy`'s value is `localhost,127.0.0.0/8,*.local,172.16.0.0/16`.

When they're not, it works as expected.

Maybe axios does not take the variables into account?

**Comment by parmentf** [comment]
That's it!

When setting `no_proxy` to `127.0.0.1`, it works!

**Comment by parmentf** [comment]
A collleague of mine wrote [fetch-with-proxy](https://github.com/touv/node-fetch-with-proxy), which has to be installed aside with isomorphic-fetch.
